### ISSUE TITLE
Python 3 code being installed by pip into Python 2.7 environment

### ISSUE THREAD

**Issue by John-Nagle** [pyserial/pyserial#128] opened 2016-06-09 21:33 UTC
Installing the current "pyserial" with pip results in an attempt to compile Python 3 code with Python 2. Note 

def open_serial_connection(*,"

which is not legal Python 2.7. Bare "*" for parameters is a Python 3 only feature.

Pyserial documentation claims, at "https://github.com/pyserial/pyserial/blob/master/CHANGES.rst", that "The source code is compatible to the 2.x and 3.x series without any changes.", but this is not the case.

While the test below was an upgrade, the same problem occurs on a clean install of pyserial on a new machine.

> sudo pip install pyserial --upgrade
> Downloading/unpacking pyserial from https://pypi.python.org/packages/aa/e7/e3109a5db1d76f459987ee3def5a34cd4ea825ac2320bd0704a8189cbc15/pyserial-3.1-py2.py3-none-any.whl#md5=dd199d56fbb257b3277690bcb8591f36
>   Downloading pyserial-3.1-py2.py3-none-any.whl (93kB): 93kB downloaded
> Installing collected packages: pyserial
>   Found existing installation: pyserial 2.6
>     Not uninstalling pyserial at /usr/lib/python2.7/dist-packages, owned by OS
> Compiling /tmp/pip_build_root/pyserial/serial/aio.py ...
>   File "/tmp/pip_build_root/pyserial/serial/aio.py", line 366
>     def open_serial_connection(*,
>                                 ^
> SyntaxError: invalid syntax
> 
> Successfully installed pyserial
> Cleaning up...

**Comment by John-Nagle** [comment] 2016-06-09 21:49
Here's the update that caused the problem:

https://github.com/pyserial/pyserial/commit/981a321a877fbe9c0322bd819d3161bfb8d592eb

"aio.py" is Python 3 only and won't compile on Python 3, but is being included in installs on Python 2.7.

**Comment by zsquareplusc** [comment] 2016-06-09 22:13
duplicate of #123

**Closed** 2016-06-11 19:27 UTC

**Comment by rob-smallshire** [comment] 2016-06-13 11:02
I've submitted #131 which modifies the install script to not install aio when running on Python 2. This will allow us to continue to use Python 3 syntax in the aio module, which will only ever work on Python 3.4+ anyway.
