### ISSUE TITLE
Not able to connect after last kernel upgrade

### ISSUE THREAD

**Issue by eze-eoc** [pyserial/pyserial#17] opened 2015-09-29 14:52 UTC
Hi
I upgraded ubuntu today, which included a new kernel, and since then, I haven't been able to connect to a 3D printer using pyserial. I receive
```
SerialException: device reports readiness to read but returned no data (device disconnected?)
```
Just in case, the fact that this is a 3D printer is transparent. It just publishes a virtual serial device the printer connects to.
My environment is:
```
Python 2.7.6
Kernel 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:51:54 UTC 2015 i686 i686 i686 GNU/Linux
$ dpkg -l | fgrep pyserial
ii  python-serial                                                             2.6-1build1                                         all          pyserial - module encapsulating access for the serial port
```
The device is connected using the USB to serial driver. Tried both using a tipical USB and an additional FTDI programmer to ensure it was not because of the cable or the board input.
I'm not sure if this is a pyserial bug, but decided it would be better if you evaluated it. I could connect using screen command executing:
screen /dev/ttyACM0 115200
or using the external FTDI programmer
screen /dev/ttyUSB0 115200
In both cases I could connect. so, it doesn't seem to be a global scale problem. However, I couldn't connect using pyserial applications, like printrun/pronterface (a python based 3D printer client) or miniterm.py.
As a workaround, I modified the file serialposix.py, and commented a few lines:
```python
            if not ready:
                break   # timeout
            buf = os.read(self.fd, size-len(read))
            # read should always return some data as select reported it was
            # ready to read when we get to this point.
            if not buf:
                # Disconnected devices, at least on Linux, show the
                # behavior that they are always ready to read immediately
                # but reading returns nothing.
                raise SerialException('device reports readiness to read but returned no data (device disconnected?)')
            read.extend(buf)
        return bytes(read)
```
Changed those to:
```python
            if not ready:
                break   # timeout
            buf = os.read(self.fd, size-len(read))
            # read should always return some data as select reported it was
            # ready to read when we get to this point.
            #if not buf:
                # Disconnected devices, at least on Linux, show the
                # behavior that they are always ready to read immediately
                # but reading returns nothing.
                #raise SerialException('device reports readiness to read but returned no data (device disconnected?)')
            read.extend(buf)
        return bytes(read)
```
and then it worked.
I know those lines should be there, but they seem to be related to the symptoms of not being able to connect to the device. Maybe this helps you to find out what the problem is, and if this has to do with pyserial, the kernel or another project.
Thanks in advance!

**Comment by eze-eoc** [comment] 2015-09-29 20:29
Improved workaround for anyone who faces this issue in case it's not fixed soon:
```python
            if not ready:
                break   # timeout
            buf = os.read(self.fd, size-len(read))
            # read should always return some data as select reported it was
            # ready to read when we get to this point.
            toto = time.time() + 10
            while not buf:
                timeleft = toto - time.time()
                if timeleft < 0:
                    raise SerialException('device reports readiness to read but returned no data (device disconnected?)')
                buf = os.read(self.fd, size-len(read))
            read.extend(buf)
```
This gives a 10 second timeout (change at will depending on the case). The previous version had problems disconnecting the miniterm from the serial device.

**Comment by pohmelie** [comment] 2015-09-30 09:56
Approve this. Have no idea why, but my old code, which works just fine couple months ago, crashes for two or three weeks. Also, fix does not work for me, after some time I have
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/serial/serialposix.py", line 468, in read
    buf = os.read(self.fd, size-len(read))
BlockingIOError: [Errno 11] Resource temporarily unavailable
```
minicom have no problems, and seems there is something «tricky»
``` shell
[broomrider ~]$ uname -a
Linux 065-pc 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:50:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[broomrider ~]$ python3 --version
Python 3.4.3
```

**Comment by zsquareplusc** [comment] 2015-09-30 14:27
Please upgrade to the latest version, available here, for further tests. It may be that the bug is already fixed. At least the second problem with `EAGAIN` (errno 11) should be fixed.

**Comment by eze-eoc** [comment] 2015-09-30 14:45
The same happened with pronterface, but couldn't test with the miniterm. Commenting the same lines made it work again. The only differences are that
* Now I can't run miniterm.py. I get
```
Traceback (most recent call last):
  File "/usr/local/bin/miniterm.py", line 23, in <module>
    from . import hexlify_codec
ValueError: Attempted relative import in non-package
```
hexlify_codec is in tools directory, but for some reason it's not taking it.
* Also when I comment the same lines as before as a workaround, it seems to be able to disconnect faster than before. Previously it seemed to get blocked, but now it disconnects very quickly.

**Comment by zsquareplusc** [comment] 2015-09-30 14:48
start miniterm as `python -m serial.tools.miniterm ...` and the relative import will work (but maybe i should remove that one anyway, its the only one, all others are absolute)

**Comment by eze-eoc** [comment] 2015-09-30 14:52
It happens the same as before
```
Exception in thread rx:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/idlt/instalacion2/pyserial/pyserial/serial/tools/miniterm.py", line 402, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 494, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```
Commenting the lines works, but also blocks when disconnecting (it's reasonable)

**Comment by pohmelie** [comment] 2015-09-30 14:56
Commenting causes high cpu load, since we do not wait in select at all, I think.

**Comment by pohmelie** [comment] 2015-10-01 10:32
Also, access to the /dev/ttyS0 via windows virtualbox from ubuntu 14.04 causes same high CPU load.

**Comment by zsquareplusc** [comment] 2015-10-04 20:43
I also see that problem, but it only seems to affect the kernel from Ubuntu 14.04 LTS with updates (that exact kernel version or even Ubuntu specific), at least the newer kernel on the Raspi still works as expected as did all older ones for many years. Also looking at the launchpad.net bug tracker, it seems to be an Ubuntu specific issue than may be fixed with the next kernel update.

``PosixPollSerial`` still works as expected but ``poll`` is not supported properly on some other platforms.
So as a temporary workaround you can either boot to a previous kernel or import ``PosixPollSerial as Serial`` (though that's not really nice for cross platform compatibility :/ )

I've tried some different settings and could not get it to work otherwise, so i'll wait a moment and hope for a fix in the next Ubuntu kernel, before I toss away an implementation that worked on many posix systems over many years...

**Comment by zsquareplusc** [comment] 2015-10-19 19:19
Looks like 3.13.0-66 is fixing that issue. The Kernel arrived in 14.04 LTS today (and was available for some time in trusty-proposed)

**Closed by zsquareplusc** 2015-10-19 19:19 UTC

**Comment by jhagberg** [comment] 2016-04-28 08:34
This bug is back in Ubuntu 16.04 
uname -a
Linux greger 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 495, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by daald** [comment] 2016-04-28 10:29
@jhagberg I was using miniterm.py a lot this week and didn't have any problems (but in the past, I had them too, with the same hardware). Maybe your problem has a different source?

me$ dpkg -s python-serial
Package: python-serial
Status: install ok installed
Version: 3.0.1-1

me$ uname -a
Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

me$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by limpkin** [comment] 2016-05-22 15:05
getting the same issue, following that thread.

**Comment by flagos** [comment] 2016-08-03 18:33
Same issue here on an up to date 16.04.

I made a fork version with the raise commented as suggested in first post just the time of having this issue properly patched. You can install it this way:
pip install -e git+https://github.com/flagos/pyserial.git#egg=pyserial

**Comment by zsquareplusc** [comment] 2016-08-07 23:12
I have also updated to 16.4.1, but I can not reproduce the issue.

I have a more recent Kernel:
Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

As a workaround, you may also try the `alt://` protocol with `VTIMESerial`, e.g. `alt:///dev/ttyUSB0\?class=VTIMESerial` (if your app uses a timeout or using git master if it has no timeout)

**Comment by playaspec** [comment] 2017-01-05 04:32
Landed here because I have been experiencing the _same_ error "_device reports readiness to read but returned no data (device disconnected?)_" over the last couple of days. In my case, the device works _most_ of the time, but fails sporadically. I'm running a Python data logger saving CSV strings from an Arduino to disk. Host running 16.04 with 4.4.0-53 kernel. Python 2.7.12.

The logger seems to die randomly with the exact error message, but in looking for answers here, I believe I've figured it out. I checked the kernel ring buffer, and sure enough there are USB error messages with the **EXACT** time as the last entry in my log file.

> [Wed Jan  4 21:55:29 2017] usb usb3-port1: disabled by hub (EMI?), re-enabling...

I'm logging the power consumption and energy expended to keep a refrigerator at temperature. Sometimes when the compressor starts up, the EMI gets into the USB cable and interrupts enough traffic to force the kernel to drop the device. The Arduino resets and a moment later logs a re-insert. This is enough to make pyserial lose it's lunch.

I don't see this as a bug, but more of a missing feature. Ideally, pyserial should handle removal/insertion events (and EMI that causes the system to drop devices) more gracefully (maybe it does, but I haven't dug into it). Pyserial has provisions to specify VIP/PID and serial number. This is more than enough info to ensure  that when the device coms back online, the program using pyserial can continue on.

Anyway, hope this helps

**Comment by jhagberg** [comment] 2017-01-11 17:34
Thanks. It helps since I now think I have the same issue. I have several freezers and when the compressor turns on I get a glitch and the sounds pauses from the computer since I use SPDIF over a RCA cabel to my  sound system. It is probably the freezers that mess upp the USB connection. Thanks! @playaspec :1st_place_medal:

**Comment by jwatte** [comment] 2017-03-16 18:03
I see this happen for the Cura 2.4 application on latest Ubuntu 16.04 on 2/15/2017.
There are no freezers or compressors involved, just a 3D printer driven by the Printrboard (which is an AVR USB device, different from the Arduinos but related.)
My guess is that this is actually a mis-match between pyserial expectations and kernel driver behaviors.
It's reasonable for character devices to return 0 data for a read request, and I think pyserial should just deal with that.
If you're worried about an infinite read-nothing loop, then detect "no data," usleep for 100 microseconds, and retry. You may even want to use this as a signal to close and re-open the file descriptor, and if re-open fails, then actually die.

**Comment by zsquareplusc** [comment] 2017-03-16 21:10
About the "expectations".

pySerial uses `select` on POSIX and expects that when it signals "ready-to-read", that either actual data is available or otherwise its interpreted as fatal fault and thus an exception is raised. Early versions of pySerial just did read again and then you'd end up in 100% CPU load when someone unplugged the USB-Serial adapter. Not a good thing and no chance for the application to do anything about. Now you have the exception and can decide in the application what to do, e.g. close and try to reopen the port.

Actually `poll` would have nicer properties, such as separate flags for "ready-to-read" and "error". I tried to use that one but it turns out that some fruity OS and hardware vendor decided to not support that part of POSIX... and I rather have the same behavior on all POSIXy systems that have an other differently behaving implementation. But if someone wants to try `poll` on a system that actually implements that call (such as Linux), you can try it out with [`alt:///dev/ttyUSB0?class=PosixPollSerial`](http://pyserial.readthedocs.io/en/latest/url_handlers.html#alt)

**Comment by jwatte** [comment] 2017-03-16 21:25
Problem is, I can 't change the application, because it's delivered as a "baked" AppImage.
Also, select() has the "exception" file descriptor list, separate from the "read" file descriptor list.
I don't know what's actually going on in this case, because gtkterm works fine, as does "dd" into the serial port, as does custom C++ programs that talk to the serial port (using termios.)
So, to me, it seems like pyserial is not providing the same behavior as you'd expect from other programs.
Separately, I don't even understand why select() is needed. If you want timeouts on reading a serial port, that's what VTIME is for, and Python doesn't expose a globally multiplexed asynchronous I/O model like Node or Haskell.

**Comment by zsquareplusc** [comment] 2017-03-17 00:31
I think the "exception" descriptor did work for errors, it's for "out of band data".

I use select because VTIME is not very flexible and has a limited range of possible timeouts. But you could try it using `alt:///dev/ttyUSB0?class=VTIMESerial` as port, if the application internally uses `serial_for_url()`.

**Comment by jwatte** [comment] 2017-03-17 00:48
Well, most other programs work great, and don't use select(), whereas pyserial has this problem pop up in a number of different situations over different years, and uses select().
From a general code robustness point of view, I would suggest you have enough data to now know that select() was a mistake and use VTIME instead. When select() was initially used, it's pretty clear that wasn't a well documented shortcoming!
Anyway, no, I can't try it myself, because the program I'm using, Cura v2.4, is delivered as an AppImage, which I can't edit, and it doesn't even allow me to configure the port name to use.

**Comment by ender210** [comment] 2017-03-26 02:50
Go to the Cura archives and get the last version of cura 15. Then make the patches to pyserial. That's where i am, but i don't know what changes to make.

**Comment by qt1** [comment] 2018-08-30 02:51
My 16.04 started with this today, and after upgrade to 18.04 it actually got worse :(

Now is get
   'device reports readiness to read but returned no data '
also with a couple of FTDI's including the ESP dev card.

And also device busy and other stuff.
Also gets disconnected after a few minutes.
