### ISSUE TITLE
miniterm.py fails to exit on failed serial port

### ISSUE THREAD

**Issue by blackketter** [pyserial/pyserial#107] opened 2016-04-25 18:26 UTC
Using minterm.py to connect to a serial USB device displays the following error when the device is unplugged:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/pyserial-2.7-py2.7.egg/EGG-INFO/scripts/miniterm.py", line 245, in reader
  File "build/bdist.macosx-10.10-intel/egg/serial/serialposix.py", line 485, in read
    raise SerialException('read failed: %s' % (e,))
SerialException: read failed: [Errno 6] Device not configured
```
Unfortunately, miniterm does not exit at this point, and waits for a failure in sending before exiting. (i.e. You have to tap a key to quit.)

Minterm should probably exit immediately so that the connection can be reestablished without requiring user input.

(This is related to the PlatformIO issue https://github.com/platformio/platformio/issues/625#issuecomment-214032221 as PlatformIO uses miniterm to connect to systems under development.)

**Comment by zsquareplusc** [comment] 2016-04-25 19:36
That's true and I actually like that behavior on Windows... so one can read the error message and the console window is not closing automatically...

Though, if the error happens on `open`, it will exit immediately, it only waits once the reader thread is running.

The reason it is this way is that miniterm uses a separate reader thread for `stdin`, respectively platform specific code to read single characters. And there does not seem to be a cross platform way to get out of that reading function. It would be needed to send a signal to the thread or something like that so that the function returns and the Python code can check the "alive" flag.

**Comment by blackketter** [comment] 2016-04-25 20:18
I understand that this might be useful behavior when mintier is run interactively from the command line, but when it's used as part of a larger script workflow, it feels broken when you can't recover to try again automatically when a device goes offline and comes back on.

If it's hard to change the current default behavior, perhaps a command-line option that exits immediately on a SerialException failure?

**Comment by zsquareplusc** [comment] 2016-04-25 21:07
The problem is, that the other thread hangs in an OS function (reading a character). If you find a solution for that, for all supported platforms of miniterm, i'm happy to look into this.

On Posix you may find a solution sending a signal, though I read that sending a signal to a specific thread may be, at least, tricky... A bit better may be using `fcntl.ioctl(tty, termios.TIOCSTI, xxx)` though that may not be trivial to support on all platforms (support, permissions, finding the tty).

On Windows it uses `msvcrt.getch()`, which is blocking with no timeout option and do polling with `msvcrt.kbhit()` does not feel right at all...

A solution should not need 3rd party modules and not be larger than the rest of the code ;-)

**Comment by ivankravets** [comment] 2016-04-26 21:07
@zsquareplusc how is difficult to throw `SerialException('read failed: %s' % (e,))` on the higher level where I can catch it and send any signals what do you need?

**Comment by zsquareplusc** [comment] 2016-04-26 22:22
@ivankravets you'll get such an exception in the other thread.

The code already clears the `alive` flag and has a note about the other thread:
https://github.com/pyserial/pyserial/blob/master/serial/tools/miniterm.py#L436

**Comment by zsquareplusc** [comment] 2016-04-26 22:32
I just tried `ungetwch` and it blocks as expected, unfortunately. On Windows, one has to use Overlapped IO to enable multiple threads on one file handle.

**Comment by ivankravets** [comment] 2016-04-29 12:31
@zsquareplusc does this commit https://github.com/pyserial/pyserial/commit/1eb3f6b5922fe7913529e4a5839d2f3983078407 resolve this issue?

**Comment by zsquareplusc** [comment] 2016-04-29 23:16
@ivankravets no, as it's not covering posix, actually making things worse as win32 and posix are now behaving differently ;-)

**Comment by zsquareplusc** [comment] 2016-05-09 21:12
would be nice if interested developers would review the commit above (16a8b5e), i'm considering using the same method on the serial port itself too, that would allow to implement a `cancel_read()` (already implemented on win32). so no more read with timeout needed just to check an "alive" flag, which would save a few CPU cycles and make aborting a read loop faster.

to make it well, it would probably be needed to clear the pipe (tcdrain) before each `read` call, so that `cancel_read` can be used repeatedly and only cancel the current `read` call.

**Comment by ivankravets** [comment] 2016-05-11 10:00
@zsquareplusc thanks a lot! I've just tested the latest development version and it works for me.

@blackketter Could you try?
```
pip uninstall pyserial
pip install https://github.com/pyserial/pyserial/archive/master.zip
```

Does it work for you?

**Comment by ivankravets** [comment] 2016-05-11 10:03
@zsquareplusc I see very strange incompatible problem with PySerial 3.1a0 and Python 2.7
```
> miniterm.py --port /dev/null
Error: "port" must be None or a string, not <type 'unicode'>
```

Could you cast `port` automatically to String?

**Comment by zsquareplusc** [comment] 2016-05-11 13:13
@ivankravets that `miniterm.py` seems to be an older file? b/c `--port` is not supported in current version. but the check was bad, using `basestr` instead of `basestring` that actually exists... fixed

**Comment by blackketter** [comment] 2016-05-11 15:17
Works great on the RasPi2 here.  Thanks!

**Comment by ivankravets** [comment] 2016-05-11 15:26
@zsquareplusc 

> but the check was bad, using basestr instead of basestring that actually exists... fixed

Thanks a lot! It works now without any problems!

**Comment by jrobeson** [comment] 2016-05-19 21:25
can this bug be closed now? or gonna wait tila new release is tagged?

**Comment by zsquareplusc** [comment] 2016-05-28 20:10
released fixes with 3.1.0

**Closed by zsquareplusc** 2016-05-28 20:10 UTC

**Comment by ivankravets** [comment] 2016-05-28 20:18
@zsquareplusc thanks a lot! 👍

**Comment by ivankravets** [comment] 2016-05-28 20:19
@blackketter @jrobeson please update package via `pip install -U pyserial`
