### ISSUE TITLE
python exception while reading psuedo terminals

### ISSUE THREAD

**Issue by rajen83** [pyserial/pyserial#76] opened 2016-02-18 00:12 UTC
In the latest pyserial code, if we try to access pseudo terminals, it bails out with following exception. I observed that in previous versions of pyserial, we do not set DTR if not specified over command line. May be we should check if the fd is a pty before trying to set DTR. Any clue while I work to solve this issue. Otherwise , pyserial with miniterm.py rocks!

root@localhost:~# miniterm.py /dev/pts/0
Traceback (most recent call last):
  File "miniterm.py", line 878, in <module>
    main()
  File "miniterm.py", line 834, in main
    serial_instance.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 311, in open
    self._update_dtr_state()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 605, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 22] Invalid argument
root@localhost:~#

**Comment by jrobeson** [comment] 2016-02-23 08:50
isn't this the same as https://github.com/pyserial/pyserial/issues/59 ?

**Comment by jrobeson** [comment] 2016-02-23 08:51
when you say latest, do you mean from the git checkout? or latest release?

**Comment by jrobeson** [comment] 2016-02-23 08:53
@zsquareplusc : if that's the case, then a new release should probably be tagged

**Comment by babca** [comment] 2016-03-05 11:41
There is still a broken 3.0.1 version in repo, so download 3.1a0 version from git.

**Comment by Peque** [comment] 2016-05-08 13:46
@zsquareplusc Maybe this should be closed as duplicate of #59?

**Comment by zsquareplusc** [comment] 2016-05-28 20:12
released 3.1 where an error setting control lines in `open()` is ignored (but not in later calls).

**Closed by zsquareplusc** 2016-05-28 20:12 UTC

**Comment by uishon** [comment] 2016-10-13 22:28
Just tried this out and still getting an error. Looks like the reason the current fix is not working is because the current code ignores IOError = 22 while I'm getting IOError = 25. See what happens when I'm trying to use the miniterm tool (just as an example):

> urii@NB-URI:~/git/csr_backend$ python -m serial.tools.miniterm /dev/pts/0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/serial/tools/miniterm.py", line 930, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/serial/tools/miniterm.py", line 886, in main
    serial_instance.open()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 265, in open
    self._update_dtr_state()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 595, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 25] Inappropriate ioctl for device
urii@NB-URI:~/git/csr_backend$

Any planned fix? Workaround?

**Comment by zsquareplusc** [comment] 2016-10-15 20:11
@uishon yes, please retry with latest release 3.2.0

**Comment by uishon** [comment] 2016-10-15 21:11
Just tried it out. It works:-) Thanks!
